/**
 * @uuid 19f1d199-0426-4331-8ff6-1be2cfe59461
 */
import BaseWriter from '../Writer';
import {GenericNodeVisitor, Text} from '../nodes';
import {Document, ElementInterface, NodeInterface} from "../types";
import {Settings} from "../../gen/Settings";
import { InvalidStateError } from "../Exceptions";
const __version__ = "";

/* eslint-disable-next-line @typescript-eslint/no-unused-vars,no-unused-vars */
const __docformat__ = "reStructuredText";

/**
 * Translator class for Pojo writer
 *  
 * @uuid 8aa67a35-4008-4669-9e89-9ff180d269ef
 */
class POJOTranslator extends GenericNodeVisitor {
    level: number;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ancestors: any[][];

    generator: string;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    warn: OmitThisParameter<(...args: any[]) => NodeInterface>;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    error: OmitThisParameter<(...args: any[]) => NodeInterface>;

    inSimple: number;
    output: {};
    settings: Settings;
    fixedText: number;
    root: {};

    /**
                  * Create a POJOTranslator
                  * @param {nodes.document} document - the document to translate
                  */
    public constructor(document: Document) {
        super(document);
        this.ancestors = [];
        this.generator = `<!-- generated by Docutils ${__version__} -->\n`;
        this.document = document;

        if (!this.document.reporter) {
            throw new Error("document has no reporter");
        }

        this.warn = this.document.reporter.warning.bind(this.document.reporter);
        this.error = this.document.reporter.error.bind(this.document.reporter);
        this.settings = document.settings;
        this.level = 0;
        this.inSimple = 0;
        this.fixedText = 0;
        this.output = {};
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase */
    public default_visit(node: ElementInterface | NodeInterface): void {
        if ((node as ElementInterface).attlist) {
            const me = [node.tagname, (node as ElementInterface).attlist(), []];
            this.ancestors.push(me);
            this.level += 1;
        }
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars */
    public default_departure(node: NodeInterface): void {
        const me = this.ancestors.pop();

        if (this.level === 1) {
            this.root = me;//          console.log(JSON.stringify(me));
        } else {
            const parent = this.ancestors[this.ancestors.length - 1];
            parent[2].push(me);
        }

        this.level -= 1;
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase */
    public visit_Text(node: Text): void {
        this.ancestors[this.ancestors.length - 1][2].push(node.astext());//      const text = escapeXml(node.astext())//      this.output.push(text);
    }

    /* eslint-disable-next-line @typescript-eslint/camelcase,camelcase,@typescript-eslint/no-unused-vars,no-unused-vars */
    public depart_Text(node: Text): void {}
}

/**
 * Writer class for POJOWriter
 *  
 * @uuid 15c8e888-c5e7-48f9-8a67-70d4f965dded
 */
class POJOWriter extends BaseWriter {
    visitor: POJOTranslator;
    translatorClass: typeof POJOTranslator = POJOTranslator;

    /**
                  * Create POJOWriter
                  * @param {Object} args - Arguments, none right now
                  */
    public constructor() {
        super();
    }

    /**
                 * Translate the document to plain old javascript object
                 */
    public translate(): void {
        const TranslatorClass = this.translatorClass;

        if (this.document === undefined) {
            throw new InvalidStateError("No document");
        }

        const visitor = new TranslatorClass(this.document);
        this.visitor = visitor;
        this.document.walkabout(visitor);
        this.output = visitor.root;
    }
}

/*
POJOWriter.settingsSpec = [
    '"Docutils-js POJO" Writer Options',
    null,
    []];

 */
export default POJOWriter;